You want to calculate the inverse of a square matrix
Use NumPy’s linear algebra inv method

In [12]:
import numpy as np
# Create matrix
matrix = np.array([[1, 4],
[2, 5]])
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

The inverse of a square matrix, A, is a second matrix A–1
, such that:
where I is the identity matrix. In NumPy we can use linalg.inv to calculate A–
1
if it exists. To see this in action, we can multiply a matrix by its inverse and the
result is the identity matrix

In [18]:
# Multiply matrix and its inverse
np.dot(matrix, np.linalg.inv(matrix))


array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [19]:
matrix @ np.linalg.inv(matrix)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])