You want to generate pseudorandom values
Use NumPy’s random


In [2]:
# Load library
import numpy as np
# Set seed
np.random.seed(0)
# Generate three random floats between 0.0 and 1.0
np.random.random(3)


array([0.5488135 , 0.71518937, 0.60276338])

NumPy offers a wide variety of means to generate random numbers, many more
than can be covered here. In our solution we generated floats; however, it is also
common to generate integers

In [3]:
# Generate three random integers between 1 and 10
np.random.randint(0, 11, 3)

array([3, 7, 9])

Alternatively, we can generate numbers by drawing them from a distribution

In [4]:
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [5]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)


array([-0.98118713, -0.08939902,  1.46416405])

In [6]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])

Finally, it can sometimes be useful to return the same random numbers multiple
times to get predictable, repeatable results. We can do this by setting the “seed”
(an integer) of the pseudorandom generator. Random processes with the same
seed will always produce the same output. We will use seeds throughout this
book so that the code you see in the book and the code you run on your
computer produces the same results