You want to multiply two matrices
Use NumPy’s dot

In [1]:
# Load library
import numpy as np
# Create matrix
matrix_a = np.array([
[1, 1],
[1, 2]])
# Create matrix
matrix_b = np.array([
[1, 3],
[1, 2]])
# Multiply two matrices
np.dot(matrix_a, matrix_b)


array([[2, 5],
       [3, 7]])

In [2]:
# Alternatively, in Python 3.5+ we can use the @ operator
matrix_a @ matrix_b

array([[2, 5],
       [3, 7]])

In [3]:
# Multiply two matrices element-wise
matrix_a * matrix_b


array([[1, 3],
       [1, 4]])