In [2]:
# You need to select one or more elements in a vector or matrix
import numpy as np
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix[1,2]

6

In [5]:
# Select the first two rows and all columns of a matrix
matrix[ :2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
# Select all rows and the second column
matrix[ :, 1:2]

array([[2],
       [5],
       [8]])

In [8]:
matrix[ :, 1]

array([2, 5, 8])