In [1]:
import numpy as np
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

In [2]:
matrix+100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [5]:
# Return maximum element
np.max(matrix)

9

In [6]:
# Return minimum element
np.min(matrix)

1

Often we want to know the maximum and minimum value in an array or subset
of an array. This can be accomplished with the max and min methods. Using the
axis parameter we can also apply the operation along a certain axis:


In [7]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [8]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])