You need to transpose a vector or matrix - Use the T method

In [1]:
import numpy as np
matrix = np.array([[1, 2, 3],
[4, 5, 6],
[7, 8, 9]])

matrix.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

Transposing is a common operation in linear algebra where the column and row
indices of each element are swapped. One nuanced point that is typically
overlooked outside of a linear algebra class is that, technically, a vector cannot
be transposed because it is just a collection of values:


In [2]:
# Transpose vector
np.array([1, 2, 3, 4, 5, 6]).T

array([1, 2, 3, 4, 5, 6])

However, it is common to refer to transposing a vector as converting a row
vector to a column vector (notice the second pair of brackets) or vice versa:

In [3]:
np.array([[1, 2, 3, 4, 5, 6]])

array([[1, 2, 3, 4, 5, 6]])

In [5]:
# Tranpose row vector
np.array([[1, 2, 3, 4, 5, 6]]).T

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])